### ISSUE TITLE
invalid response renders vshaxe dysfunctional

### ISSUE THREAD

**Issue by ousado** [vshaxe/haxe-languageserver#20]
On retrying to restart the language server I got this:
`Exception while handling request shutdown: TypeError: Cannot read property 'length' of null`
for the line linked below.
vshaxe completely stopped working for my project until I put that loop in a try/catch block. Restarts, killing haxe instances, nothing else helped.

https://github.com/vshaxe/haxe-languageserver/blob/master/src/haxeLanguageServer/features/DiagnosticsManager.hx#L38

**Comment by nadako** [comment]
Weird, I can't reproduce that. I added `data = null` in that function to reproduce the TypeError, but that only breaks diagnostics, everything else works...

**Comment by ousado** [comment]
Sorry, I forgot give an update - the error was a failed assertion in haxe, the above only "fixed" the lockup temporarily

**Comment by Gama11** [comment]
This happens for me after newly initializing a workspace using the init command...

**Comment by Gama11** [comment]
Good thing I figured out how to debug the server... Interesting chain of events:

-  `HaxeServer.restart()` -> `HaxeServer.stop()` which calls `request.processResult(null)`
- this leads to `return callback(null)`
- callback in this case was `processDiagnosticsReply`, which now gets a null value

@nadako Why does the callback need to be called there at all? I'm inclined to just remove the call.

https://github.com/vshaxe/haxe-languageserver/blob/master/src/haxeLanguageServer/HaxeServer.hx#L63

**Comment by nadako** [comment]
Actually, this is something that might need a better architectural fix, because VS Code waits for requests to be answered, so we ALWAYS need to reply/reject, so VSCode client don't have stall requests in its queue (or else bad things happen).

**Comment by Gama11** [comment]
In that case, can't we just replace the `callback` call with `errback()`?

**Comment by nadako** [comment]
We gotta research on what response vscode client expects when request is cancelled (the `token.cancelled`) check. IIRC they said that they want "some response", but I'm not sure what will happen if we reply with InternalError like most of those requests do in their errbacks.

I said we need a better architecture here also because `if (token.canceled) return;` in callbacks is also wrong, since I believe those requessts won't be removed from both client and server... But to not repeat ourselves with these checks/errbacks we need to incapsulate it somehow.

**Comment by Gama11** [comment]
I went with the errback-approach for now, since that's better than what we had before. Crashing Haxe processes are handled more smoothly now (which was the original problem here): 

![](http://i.imgur.com/c1EP7H8.png)

Feel free to open a separate issue for your architecture changes.

**Comment by Gama11** [comment]
I decided to just `return` instead of calling `errback` there for now, canceled requests happen quite frequently when hovering over stuff, resulting in a lot of log messages, which got a bit annoying.

**Comment by Gama11** [comment]
I just made this a bit smarter. Putting it in the output channel was a bit obscure, and we now also detect if the crashes happen because of invalid compiler arguments:

![](http://i.imgur.com/7gMsw8x.png)

If not, we dump the Haxe output in the output channel and show the user this message:

![](http://i.imgur.com/9WewzPf.png)
